name: "Release"

on:
  push:
    tags:
      - "*.*.*"

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ORG: nuvlabox

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Multi-arch docker image build prerequired
        run: sudo docker run --privileged linuxkit/binfmt:v0.7

      - name: Build on amd64
        env:
          PLATFORM: amd64
        run: ./.ci/build.sh

      - name: Build on arm64
        env:
          PLATFORM: arm64
        run: ./.ci/build.sh

      - name: Build on arm
        env:
          PLATFORM: arm
        run: ./.ci/build.sh

      - name: Deploy
        env:
          PLATFORM: "amd64 arm arm64"
        run: ./.ci/push.sh


  notify:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          icon_emoji: ':rocket:'